public class AccountSampleCls {
    //variable declarations
    public string AccountName = 'GenePoint';
    public string Rating = 'Cold';
    public string Phone = '(650) 867-3450';
    public string Website = 'http://www.genepoint.com';
    public string BillingStreet = 'Mountain View'; 
    public id parentaccount = '0014x000006fHRl';//Edge Communications
    public date currentdate = system.today();
    public datetime currentdatetime = system.now();
}